project_name: wg-ui
release:
  github:
    owner: UnAfraid
    name: wg-ui
  name_template: '{{.Tag}}'
builds:
  - id: release
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    gomips:
      - softfloat
      - hardfloat
  - id: docker-release
    binary: app
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
nfpms:
  - id: default
    homepage: https://github.com/UnAfraid/wg-ui
    maintainer: Rumen Nikiforov <unafraid89@gmail.com>
    description: wg-ui - Self-contained WireGuard management service with a web UI and GraphQL API written in pure Go.
    license: "MIT"
    builds:
      - release
    formats:
      - deb
      - archlinux
    bindir: /usr/bin
    contents:
      - src: .env.dist
        dst: /etc/default/wg-ui
      - src: build/scripts/systemd/wg-ui.service
        dst: /etc/systemd/system/wg-ui.service
    scripts:
      postinstall: build/scripts/debian/postinstall.sh
      preremove: build/scripts/debian/preremove.sh
      postremove: build/scripts/debian/postremove.sh
    overrides:
      archlinux:
        scripts:
          postinstall: build/scripts/archlinux/postinstall.sh
          preremove: build/scripts/archlinux/preremove.sh
          postremove: build/scripts/debian/postremove.sh
    archlinux:
      pkgbase: wg-ui
      packager: Rumen Nikiforov <unafraid89@gmail.com>
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
  algorithm: sha512
changelog:
  sort: asc
  filters:
    exclude:
      - '^ci:'
      - '^docs?:'
      - '^readme:'
      - '^tests?:'
      - Merge pull request
      - Merge branch
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- .Arch }}
      {{- if eq .Arch "mips" }}_{{- title .Mips }}{{ end }}
      {{- if eq .Arch "mipsle" }}_{{- title .Mips }}{{ end }}
      {{- if eq .Arch "mips64" }}_{{- title .Mips }}{{ end }}
      {{- if eq .Arch "mips64le" }}_{{- title .Mips }}{{ end }}
    builds:
      - release
    files:
      - .env.dist
      - LICENSE
      - README.md
