project_name: wg-ui
release:
  github:
    owner: UnAfraid
    name: wg-ui
  name_template: '{{.Tag}}'
builds:
  - id: release
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: docker-release
    binary: app
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
archives:
  - rlcp: true
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS_
      {{- else }}{{- title .Os }}_{{ end }}
      {{- .Arch }}
    builds:
      - release
    files:
      - .env.dist
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip
