name: Go

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.0

      - name: Download dependencies
        run: go mod download

      - name: Test
        env:
          CGO_ENABLED: 0
        run: go test ./...

      - name: Test Race
        run: go test -race ./...
